### ISSUE TITLE
Syntax error line 636

### ISSUE THREAD

**Issue by zopar** [mgedmin/profilehooks#15]
Hi
the problem is 
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/profilehooks.py', 636, 23, '        lines = {ln for off, ln in dis.findlinestarts(self.fn.__code__)\n'))

Line 636/7
lines = {ln for off, ln in dis.findlinestarts(self.fn.__code__)
                 if ln not in strs}

We need to replace { with [
I will pull a merge requests

I used python 2.6.6 you could test also compatibility with 2.6 if you like

**Comment by mgedmin** [comment]
Profilehooks dropped Python 2.6 support in version 1.9.0.  You can still use 1.8.1 if you're stuck on 2.6 (but you should upgrade to 2.7 or 3.x).
