### ISSUE TITLE
Cannot use decorators inside a class..

### ISSUE THREAD

**Issue by projx** [mgedmin/profilehooks#18]
Hi

I'm trying to use the @timecall() decoractor in a class, as follows:

    @timecall(immediate=True)
    def toggle_sort(self):
        checked = self.actionToggleSort.isChecked()
        if checked==True:

But its returning the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/profilehooks.py", line 736, in new_fn
    return fp(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/profilehooks.py", line 762, in __call__
    return fn(*args, **kw)
TypeError: toggle_sort() takes 1 positional argument but 2 were given
```

Could you advise if I'm doing anything wrong? Is this a bug?

Unfortunately I'm a python newb, so its probably just something I've missed.

Thanks

**Comment by mgedmin** [comment]
This should work.

Could you provide a self-contained example that I could run to reproduce the error?
