### ISSUE TITLE
UnicodeDecodeError on output

### ISSUE THREAD

**Issue by eboth** [mgedmin/profilehooks#24]
Even with the console set to UTF-8, profilehooks hits an exception on outputting `@coverage` results:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python3-32\lib\site-packages\profilehooks.py", line 632, in __init__
    self.find_source_lines()
  File "C:\Python3-32\lib\site-packages\profilehooks.py", line 640, in find_source_lines
    strs = self._find_docstrings(self.filename)
  File "C:\Python3-32\lib\site-packages\profilehooks.py", line 658, in _find_docstrings
    for ttype, tstr, start, end, line in tokens:
  File "C:\Python3-32\lib\tokenize.py", line 450, in _tokenize
    line = readline()
  File "C:\Python3-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3355: character maps to <undefined>
```

`@profile` results print fine, as does printing unicode to the console:
`print('\u0173\u2014\u0172')`

**Environment:**
Windows 7 x64
Python x32 3.8.1
profilehooks 1.11.0
Console: conemu or IntelliJ IDEA
Some encoding settings (don't ask me about the difference between them, though at first sight `sys.stdout.encoding` seems a good candidate for deciding on the console output encoding):
```
>>> import sys; sys.getdefaultencoding()
'utf-8'
>>> import locale; locale.getpreferredencoding()
'cp1252'
>>> sys.stdout.encoding
'utf-8'
```

Maybe the "Note" about `surrogateescape` under [this link](http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#files-in-an-ascii-compatible-encoding-best-effort-is-acceptable) would also apply?

**Comment by eboth** [comment]
As a workaround, the following hack (as per [StackOverflow](https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows/34345136#answer-34345136)) makes the error go away:
```
import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])
```

**Comment by mgedmin** [comment]
Ah, yes, _find_docstrings(), the cursed function.  It should be using `tokenize.open()` instead of `open()` to correctly detect the source file encoding.

Now how do I write a unit test for this bug??

**Comment by mgedmin** [comment]
Can you try git master to see if this is fixed?

**Comment by eboth** [comment]
Yes it is - great job, just as with the overall package which is really brilliant. Thanks a lot!!

**Comment by mgedmin** [comment]
I'll cut a new release then.
