### ISSUE TITLE
suggested enhancement: option to turn off output to stdout

### ISSUE THREAD

**Issue by lebedov** [mgedmin/profilehooks#5]
It would be nice to be able to turn off all output to stdout in situations when one only wishes to save profiling data to a file, e.g., for long-running programs that don't emit output by default.

**Comment by mgedmin** [comment]
Something like `@profile(filename='prof.out', stdout=False)`?

**Comment by lebedov** [comment]
Yes.

**Comment by mgedmin** [comment]
So this is implemented but, um, I'm lazy and I didn't actually test that it works.

(Tests work, coverage remains 100%, but that doesn't necessarily mean I didn't mess it up in some way ;)

**Comment by lebedov** [comment]
Thanks - confirming that it works.
